// <auto-generated />
using System;
using LabManagement.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabManagement.DAL.Migrations
{
    [DbContext(typeof(LabManagementDbContext))]
    [Migration("20250929040237_Remove_department_table")]
    partial class Remove_department_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabManagement.DAL.Models.ActivityType", b =>
                {
                    b.Property<int>("ActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("activity_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ActivityTypeId")
                        .HasName("PK__activity__D2470C87E6BFD9E2");

                    b.ToTable("activity_types", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.EventParticipant", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Role")
                        .HasColumnType("decimal(2, 0)")
                        .HasColumnName("role");

                    b.HasKey("EventId", "UserId")
                        .HasName("PK__event_pa__C8EB1457151547CC");

                    b.HasIndex("UserId");

                    b.ToTable("event_participants", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Lab", b =>
                {
                    b.Property<int>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("LabId")
                        .HasName("PK__labs__66DE64DB63EAC51C");

                    b.HasIndex("ManagerId");

                    b.ToTable("labs", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int")
                        .HasColumnName("activity_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int")
                        .HasColumnName("organizer_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    b.HasKey("EventId")
                        .HasName("PK__lab_even__2370F7270A85F029");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("LabId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("ZoneId");

                    b.ToTable("lab_events", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabZone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ZoneId")
                        .HasName("PK__lab_zone__80B401DF8DC1AAD7");

                    b.HasIndex("LabId");

                    b.ToTable("lab_zones", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int")
                        .HasColumnName("recipient_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("NotificationId")
                        .HasName("PK__notifica__E059842F54DF105B");

                    b.HasIndex("EventId");

                    b.HasIndex("RecipientId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("int")
                        .HasColumnName("generated_by");

                    b.Property<int?>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("report_type");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    b.HasKey("ReportId")
                        .HasName("PK__reports__779B7C58021353BD");

                    b.HasIndex("GeneratedBy");

                    b.HasIndex("LabId");

                    b.HasIndex("ZoneId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.SecurityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("action");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("photo_url");

                    b.Property<int>("SecurityId")
                        .HasColumnType("int")
                        .HasColumnName("security_id");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LogId")
                        .HasName("PK__security__9E2397E0DFE7202D");

                    b.HasIndex("EventId");

                    b.HasIndex("SecurityId");

                    b.ToTable("security_logs", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("password_hash");

                    b.Property<decimal>("Role")
                        .HasColumnType("decimal(2, 0)")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370F20E930E3");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164DB54CFBB")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.EventParticipant", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.LabEvent", "Event")
                        .WithMany("EventParticipants")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__event_par__event__151B244E");

                    b.HasOne("LabManagement.DAL.Models.User", "User")
                        .WithMany("EventParticipants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__event_par__user___160F4887");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Lab", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.User", "Manager")
                        .WithMany("Labs")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK__labs__manager_id__06CD04F7");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabEvent", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.ActivityType", "ActivityType")
                        .WithMany("LabEvents")
                        .HasForeignKey("ActivityTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_event__activ__114A936A");

                    b.HasOne("LabManagement.DAL.Models.Lab", "Lab")
                        .WithMany("LabEvents")
                        .HasForeignKey("LabId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_event__lab_i__0F624AF8");

                    b.HasOne("LabManagement.DAL.Models.User", "Organizer")
                        .WithMany("LabEvents")
                        .HasForeignKey("OrganizerId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_event__organ__123EB7A3");

                    b.HasOne("LabManagement.DAL.Models.LabZone", "Zone")
                        .WithMany("LabEvents")
                        .HasForeignKey("ZoneId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_event__zone___10566F31");

                    b.Navigation("ActivityType");

                    b.Navigation("Lab");

                    b.Navigation("Organizer");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabZone", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.Lab", "Lab")
                        .WithMany("LabZones")
                        .HasForeignKey("LabId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_zones__lab_i__09A971A2");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Notification", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.LabEvent", "Event")
                        .WithMany("Notifications")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__notificat__event__208CD6FA");

                    b.HasOne("LabManagement.DAL.Models.User", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .IsRequired()
                        .HasConstraintName("FK__notificat__recip__1F98B2C1");

                    b.Navigation("Event");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Report", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.User", "GeneratedByNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("GeneratedBy")
                        .IsRequired()
                        .HasConstraintName("FK__reports__generat__245D67DE");

                    b.HasOne("LabManagement.DAL.Models.Lab", "Lab")
                        .WithMany("Reports")
                        .HasForeignKey("LabId")
                        .HasConstraintName("FK__reports__lab_id__25518C17");

                    b.HasOne("LabManagement.DAL.Models.LabZone", "Zone")
                        .WithMany("Reports")
                        .HasForeignKey("ZoneId")
                        .HasConstraintName("FK__reports__zone_id__2645B050");

                    b.Navigation("GeneratedByNavigation");

                    b.Navigation("Lab");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.SecurityLog", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.LabEvent", "Event")
                        .WithMany("SecurityLogs")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__security___event__19DFD96B");

                    b.HasOne("LabManagement.DAL.Models.User", "Security")
                        .WithMany("SecurityLogs")
                        .HasForeignKey("SecurityId")
                        .IsRequired()
                        .HasConstraintName("FK__security___secur__1AD3FDA4");

                    b.Navigation("Event");

                    b.Navigation("Security");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.ActivityType", b =>
                {
                    b.Navigation("LabEvents");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Lab", b =>
                {
                    b.Navigation("LabEvents");

                    b.Navigation("LabZones");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabEvent", b =>
                {
                    b.Navigation("EventParticipants");

                    b.Navigation("Notifications");

                    b.Navigation("SecurityLogs");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabZone", b =>
                {
                    b.Navigation("LabEvents");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.User", b =>
                {
                    b.Navigation("EventParticipants");

                    b.Navigation("LabEvents");

                    b.Navigation("Labs");

                    b.Navigation("Notifications");

                    b.Navigation("Reports");

                    b.Navigation("SecurityLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
