// <auto-generated />
using System;
using LabManagement.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabManagement.DAL.Migrations
{
    [DbContext(typeof(LabManagementDbContext))]
    [Migration("20251020031626_ConvertAllEnumColumnsToInt")]
    partial class ConvertAllEnumColumnsToInt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabManagement.DAL.Models.ActivityType", b =>
                {
                    b.Property<int>("ActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("activity_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ActivityTypeId")
                        .HasName("PK__activity__D2470C8792B1F20E");

                    b.ToTable("activity_types", (string)null);

                    b.HasData(
                        new
                        {
                            ActivityTypeId = 1,
                            Description = "Hands-on training session",
                            Name = "Workshop"
                        },
                        new
                        {
                            ActivityTypeId = 2,
                            Description = "Educational seminar or lecture",
                            Name = "Seminar"
                        },
                        new
                        {
                            ActivityTypeId = 3,
                            Description = "Research activity",
                            Name = "Research"
                        },
                        new
                        {
                            ActivityTypeId = 4,
                            Description = "Laboratory experiment",
                            Name = "Experiment"
                        },
                        new
                        {
                            ActivityTypeId = 5,
                            Description = "Group meeting or discussion",
                            Name = "Meeting"
                        });
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    b.HasKey("BookingId")
                        .HasName("PK__bookings__5DE3A5B17836BDD3");

                    b.HasIndex("LabId");

                    b.HasIndex("UserId");

                    b.HasIndex("ZoneId");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("equipment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("EquipmentId")
                        .HasName("PK__equipmen__197068AFC616B45E");

                    b.HasIndex("LabId");

                    b.HasIndex(new[] { "Code" }, "UQ__equipmen__357D4CF958F5304E")
                        .IsUnique();

                    b.ToTable("equipment", (string)null);

                    b.HasData(
                        new
                        {
                            EquipmentId = 1,
                            Code = "EQ-001",
                            Description = "Digital microscope with 1000x magnification",
                            LabId = 1,
                            Name = "Microscope",
                            Status = 1
                        },
                        new
                        {
                            EquipmentId = 2,
                            Code = "EQ-002",
                            Description = "High-speed centrifuge",
                            LabId = 1,
                            Name = "Centrifuge",
                            Status = 1
                        },
                        new
                        {
                            EquipmentId = 3,
                            Code = "EQ-003",
                            Description = "Workstation with development tools",
                            LabId = 2,
                            Name = "Computer Station",
                            Status = 1
                        },
                        new
                        {
                            EquipmentId = 4,
                            Code = "EQ-004",
                            Description = "Network server infrastructure",
                            LabId = 2,
                            Name = "Server Rack",
                            Status = 1
                        });
                });

            modelBuilder.Entity("LabManagement.DAL.Models.EventParticipant", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.HasKey("EventId", "UserId")
                        .HasName("PK__event_pa__C8EB1457D657AA72");

                    b.HasIndex("UserId");

                    b.ToTable("event_participants", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Lab", b =>
                {
                    b.Property<int>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("LabId")
                        .HasName("PK__labs__66DE64DB381C94E8");

                    b.HasIndex("ManagerId");

                    b.ToTable("labs", (string)null);

                    b.HasData(
                        new
                        {
                            LabId = 1,
                            Description = "Laboratory for biology experiments and research",
                            Location = "Building A - Floor 2",
                            ManagerId = 2,
                            Name = "Biology Lab"
                        },
                        new
                        {
                            LabId = 2,
                            Description = "Computer lab with 30 workstations",
                            Location = "Building B - Floor 3",
                            ManagerId = 2,
                            Name = "Computer Lab"
                        },
                        new
                        {
                            LabId = 3,
                            Description = "Chemistry laboratory with safety equipment",
                            Location = "Building A - Floor 1",
                            ManagerId = 3,
                            Name = "Chemistry Lab"
                        });
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int")
                        .HasColumnName("activity_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int")
                        .HasColumnName("organizer_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    b.HasKey("EventId")
                        .HasName("PK__lab_even__2370F7275CD0E23F");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("LabId");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("ZoneId");

                    b.ToTable("lab_events", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabZone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ZoneId")
                        .HasName("PK__lab_zone__80B401DFE18A342C");

                    b.HasIndex("LabId");

                    b.ToTable("lab_zones", (string)null);

                    b.HasData(
                        new
                        {
                            ZoneId = 1,
                            Description = "Main experiment area",
                            LabId = 1,
                            Name = "Zone A"
                        },
                        new
                        {
                            ZoneId = 2,
                            Description = "Storage and preparation area",
                            LabId = 1,
                            Name = "Zone B"
                        },
                        new
                        {
                            ZoneId = 3,
                            Description = "Development stations",
                            LabId = 2,
                            Name = "Zone A"
                        },
                        new
                        {
                            ZoneId = 4,
                            Description = "Server room",
                            LabId = 2,
                            Name = "Zone B"
                        },
                        new
                        {
                            ZoneId = 5,
                            Description = "Chemical storage",
                            LabId = 3,
                            Name = "Zone A"
                        });
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int")
                        .HasColumnName("recipient_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("NotificationId")
                        .HasName("PK__notifica__E059842F312DB8D7");

                    b.HasIndex("EventId");

                    b.HasIndex("RecipientId");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("int")
                        .HasColumnName("generated_by");

                    b.Property<int?>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("report_type");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    b.HasKey("ReportId")
                        .HasName("PK__reports__779B7C581E1EA1F5");

                    b.HasIndex("GeneratedBy");

                    b.HasIndex("LabId");

                    b.HasIndex("ZoneId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.SecurityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("Action")
                        .HasColumnType("int")
                        .HasColumnName("action");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("photo_url");

                    b.Property<int>("SecurityId")
                        .HasColumnType("int")
                        .HasColumnName("security_id");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("LogId")
                        .HasName("PK__security__9E2397E0366827BF");

                    b.HasIndex("EventId");

                    b.HasIndex("SecurityId");

                    b.ToTable("security_logs", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370FBC272336");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164598EED90")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@lab.com",
                            Name = "Admin User",
                            PasswordHash = "$2y$10$hHPvRxU0fb3iOGs2z2VeEuEZ0UTfBS/L6LINEkQ5uElUYJXpbSFsC",
                            Role = 0
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "schoolmanager@lab.com",
                            Name = "School Manager",
                            PasswordHash = "$2y$10$hHPvRxU0fb3iOGs2z2VeEuEZ0UTfBS/L6LINEkQ5uElUYJXpbSFsC",
                            Role = 1
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "manager@lab.com",
                            Name = "Lab Manager",
                            PasswordHash = "$2y$10$hHPvRxU0fb3iOGs2z2VeEuEZ0UTfBS/L6LINEkQ5uElUYJXpbSFsC",
                            Role = 2
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "security@lab.com",
                            Name = "Security Staff",
                            PasswordHash = "$2y$10$hHPvRxU0fb3iOGs2z2VeEuEZ0UTfBS/L6LINEkQ5uElUYJXpbSFsC",
                            Role = 3
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "member@lab.com",
                            Name = "Member",
                            PasswordHash = "$2y$10$hHPvRxU0fb3iOGs2z2VeEuEZ0UTfBS/L6LINEkQ5uElUYJXpbSFsC",
                            Role = 4
                        });
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Booking", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.Lab", "Lab")
                        .WithMany("Bookings")
                        .HasForeignKey("LabId")
                        .IsRequired()
                        .HasConstraintName("FK__bookings__lab_id__7D0E9093");

                    b.HasOne("LabManagement.DAL.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__bookings__user_i__7C1A6C5A");

                    b.HasOne("LabManagement.DAL.Models.LabZone", "Zone")
                        .WithMany("Bookings")
                        .HasForeignKey("ZoneId")
                        .IsRequired()
                        .HasConstraintName("FK__bookings__zone_i__7E02B4CC");

                    b.Navigation("Lab");

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Equipment", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.Lab", "Lab")
                        .WithMany("Equipment")
                        .HasForeignKey("LabId")
                        .IsRequired()
                        .HasConstraintName("FK__equipment__lab_i__7849DB76");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.EventParticipant", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.LabEvent", "Event")
                        .WithMany("EventParticipants")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__event_par__event__078C1F06");

                    b.HasOne("LabManagement.DAL.Models.User", "User")
                        .WithMany("EventParticipants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__event_par__user___0880433F");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Lab", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.User", "Manager")
                        .WithMany("Labs")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK__labs__manager_id__6FB49575");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabEvent", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.ActivityType", "ActivityType")
                        .WithMany("LabEvents")
                        .HasForeignKey("ActivityTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_event__activ__03BB8E22");

                    b.HasOne("LabManagement.DAL.Models.Lab", "Lab")
                        .WithMany("LabEvents")
                        .HasForeignKey("LabId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_event__lab_i__01D345B0");

                    b.HasOne("LabManagement.DAL.Models.User", "Organizer")
                        .WithMany("LabEvents")
                        .HasForeignKey("OrganizerId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_event__organ__04AFB25B");

                    b.HasOne("LabManagement.DAL.Models.LabZone", "Zone")
                        .WithMany("LabEvents")
                        .HasForeignKey("ZoneId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_event__zone___02C769E9");

                    b.Navigation("ActivityType");

                    b.Navigation("Lab");

                    b.Navigation("Organizer");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabZone", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.Lab", "Lab")
                        .WithMany("LabZones")
                        .HasForeignKey("LabId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_zones__lab_i__72910220");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Notification", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.LabEvent", "Event")
                        .WithMany("Notifications")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__notificat__event__12FDD1B2");

                    b.HasOne("LabManagement.DAL.Models.User", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .IsRequired()
                        .HasConstraintName("FK__notificat__recip__1209AD79");

                    b.Navigation("Event");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Report", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.User", "GeneratedByNavigation")
                        .WithMany("Reports")
                        .HasForeignKey("GeneratedBy")
                        .IsRequired()
                        .HasConstraintName("FK__reports__generat__16CE6296");

                    b.HasOne("LabManagement.DAL.Models.Lab", "Lab")
                        .WithMany("Reports")
                        .HasForeignKey("LabId")
                        .HasConstraintName("FK__reports__lab_id__17C286CF");

                    b.HasOne("LabManagement.DAL.Models.LabZone", "Zone")
                        .WithMany("Reports")
                        .HasForeignKey("ZoneId")
                        .HasConstraintName("FK__reports__zone_id__18B6AB08");

                    b.Navigation("GeneratedByNavigation");

                    b.Navigation("Lab");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.SecurityLog", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.LabEvent", "Event")
                        .WithMany("SecurityLogs")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__security___event__0C50D423");

                    b.HasOne("LabManagement.DAL.Models.User", "Security")
                        .WithMany("SecurityLogs")
                        .HasForeignKey("SecurityId")
                        .IsRequired()
                        .HasConstraintName("FK__security___secur__0D44F85C");

                    b.Navigation("Event");

                    b.Navigation("Security");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.ActivityType", b =>
                {
                    b.Navigation("LabEvents");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Lab", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Equipment");

                    b.Navigation("LabEvents");

                    b.Navigation("LabZones");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabEvent", b =>
                {
                    b.Navigation("EventParticipants");

                    b.Navigation("Notifications");

                    b.Navigation("SecurityLogs");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabZone", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LabEvents");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("EventParticipants");

                    b.Navigation("LabEvents");

                    b.Navigation("Labs");

                    b.Navigation("Notifications");

                    b.Navigation("Reports");

                    b.Navigation("SecurityLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
