// <auto-generated />
using System;
using LabManagement.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabManagement.DAL.Migrations
{
    [DbContext(typeof(LabManagementDbContext))]
    partial class LabManagementDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabManagement.DAL.Models.ActivityType", b =>
                {
                    b.Property<int>("ActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("activity_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityTypeId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ActivityTypeId")
                        .HasName("PK__activity__D2470C8792B1F20E");

                    b.ToTable("activity_types", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("EndTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("end_time");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("StartTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    b.HasKey("BookingId")
                        .HasName("PK__bookings__5DE3A5B17836BDD3");

                    b.HasIndex(new[] { "LabId" }, "IX_bookings_lab_id");

                    b.HasIndex(new[] { "UserId" }, "IX_bookings_user_id");

                    b.HasIndex(new[] { "ZoneId" }, "IX_bookings_zone_id");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("DepartmentId")
                        .HasName("PK__departme__C2232422");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("equipment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("EquipmentId")
                        .HasName("PK__equipmen__197068AFC616B45E");

                    b.HasIndex(new[] { "LabId" }, "IX_equipment_lab_id");

                    b.HasIndex(new[] { "Code" }, "UQ__equipmen__357D4CF958F5304E")
                        .IsUnique();

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.EventParticipant", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.HasKey("EventId", "UserId")
                        .HasName("PK__event_pa__C8EB1457D657AA72");

                    b.HasIndex(new[] { "UserId" }, "IX_event_participants_user_id");

                    b.ToTable("event_participants", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Lab", b =>
                {
                    b.Property<int>("LabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LabId"));

                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsOpen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_open");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("location");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int")
                        .HasColumnName("manager_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("LabId")
                        .HasName("PK__labs__66DE64DB381C94E8");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_labs_department_id");

                    b.HasIndex(new[] { "ManagerId" }, "IX_labs_manager_id");

                    b.ToTable("labs", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabEvent", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int>("ActivityTypeId")
                        .HasColumnType("int")
                        .HasColumnName("activity_type_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("end_time");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int")
                        .HasColumnName("organizer_id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<DateTime>("StartTime")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    b.HasKey("EventId")
                        .HasName("PK__lab_even__2370F7275CD0E23F");

                    b.HasIndex(new[] { "ActivityTypeId" }, "IX_lab_events_activity_type_id");

                    b.HasIndex(new[] { "LabId" }, "IX_lab_events_lab_id");

                    b.HasIndex(new[] { "OrganizerId" }, "IX_lab_events_organizer_id");

                    b.HasIndex(new[] { "ZoneId" }, "IX_lab_events_zone_id");

                    b.ToTable("lab_events", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabZone", b =>
                {
                    b.Property<int>("ZoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("ZoneId")
                        .HasName("PK__lab_zone__80B401DFE18A342C");

                    b.HasIndex(new[] { "LabId" }, "IX_lab_zones_lab_id");

                    b.ToTable("lab_zones", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int")
                        .HasColumnName("recipient_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("NotificationId")
                        .HasName("PK__notifica__E059842F312DB8D7");

                    b.HasIndex(new[] { "EventId" }, "IX_notifications_event_id");

                    b.HasIndex(new[] { "RecipientId" }, "IX_notifications_recipient_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("report_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("LabId")
                        .HasColumnType("int")
                        .HasColumnName("lab_id");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("photo_url");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("report_type");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int")
                        .HasColumnName("zone_id");

                    b.HasKey("ReportId")
                        .HasName("PK__reports__779B7C581E1EA1F5");

                    b.HasIndex(new[] { "LabId" }, "IX_reports_lab_id");

                    b.HasIndex(new[] { "UserId" }, "IX_reports_user_id");

                    b.HasIndex(new[] { "ZoneId" }, "IX_reports_zone_id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.SecurityLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("ActionType")
                        .HasColumnType("int")
                        .HasColumnName("action_type");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("logged_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("photo_url");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.Property<int>("SecurityId")
                        .HasColumnType("int")
                        .HasColumnName("security_id");

                    b.HasKey("LogId")
                        .HasName("PK__security__9E2397E0366827BF");

                    b.HasIndex(new[] { "EventId" }, "IX_security_logs_event_id");

                    b.HasIndex(new[] { "SecurityId" }, "IX_security_logs_security_id");

                    b.ToTable("security_logs", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("PK__users__B9BE370FBC272336");

                    b.HasIndex(new[] { "Email" }, "UQ__users__AB6E6164598EED90")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.UserDepartment", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("UserId", "DepartmentId")
                        .HasName("PK__user_dep__1EDFFB19");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_user_departments_department_id");

                    b.ToTable("user_departments", (string)null);
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Booking", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.Lab", "Lab")
                        .WithMany("Bookings")
                        .HasForeignKey("LabId")
                        .IsRequired()
                        .HasConstraintName("FK__bookings__lab_id__7D0E9093");

                    b.HasOne("LabManagement.DAL.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__bookings__user_i__7C1A6C5A");

                    b.HasOne("LabManagement.DAL.Models.LabZone", "Zone")
                        .WithMany("Bookings")
                        .HasForeignKey("ZoneId")
                        .IsRequired()
                        .HasConstraintName("FK__bookings__zone_i__7E02B4CC");

                    b.Navigation("Lab");

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Equipment", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.Lab", "Lab")
                        .WithMany("Equipment")
                        .HasForeignKey("LabId")
                        .IsRequired()
                        .HasConstraintName("FK__equipment__lab_i__7849DB76");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.EventParticipant", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.LabEvent", "Event")
                        .WithMany("EventParticipants")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__event_par__event__078C1F06");

                    b.HasOne("LabManagement.DAL.Models.User", "User")
                        .WithMany("EventParticipants")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__event_par__user___0880433F");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Lab", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.Department", "Department")
                        .WithMany("Labs")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK__labs__departmen__6EC0713C");

                    b.HasOne("LabManagement.DAL.Models.User", "Manager")
                        .WithMany("Labs")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK__labs__manager_id__6FB49575");

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabEvent", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.ActivityType", "ActivityType")
                        .WithMany("LabEvents")
                        .HasForeignKey("ActivityTypeId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_event__activ__03BB8E22");

                    b.HasOne("LabManagement.DAL.Models.Lab", "Lab")
                        .WithMany("LabEvents")
                        .HasForeignKey("LabId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_event__lab_i__01D345B0");

                    b.HasOne("LabManagement.DAL.Models.User", "Organizer")
                        .WithMany("LabEvents")
                        .HasForeignKey("OrganizerId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_event__organ__04AFB25B");

                    b.HasOne("LabManagement.DAL.Models.LabZone", "Zone")
                        .WithMany("LabEvents")
                        .HasForeignKey("ZoneId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_event__zone___02C769E9");

                    b.Navigation("ActivityType");

                    b.Navigation("Lab");

                    b.Navigation("Organizer");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabZone", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.Lab", "Lab")
                        .WithMany("LabZones")
                        .HasForeignKey("LabId")
                        .IsRequired()
                        .HasConstraintName("FK__lab_zones__lab_i__72910220");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Notification", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.LabEvent", "Event")
                        .WithMany("Notifications")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__notificat__event__12FDD1B2");

                    b.HasOne("LabManagement.DAL.Models.User", "Recipient")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientId")
                        .IsRequired()
                        .HasConstraintName("FK__notificat__recip__1209AD79");

                    b.Navigation("Event");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Report", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.Lab", "Lab")
                        .WithMany("Reports")
                        .HasForeignKey("LabId")
                        .HasConstraintName("FK__reports__lab_id__17C286CF");

                    b.HasOne("LabManagement.DAL.Models.LabZone", "Zone")
                        .WithMany("Reports")
                        .HasForeignKey("ZoneId")
                        .HasConstraintName("FK__reports__zone_id__18B6AB08");

                    b.Navigation("Lab");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.SecurityLog", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.LabEvent", "Event")
                        .WithMany("SecurityLogs")
                        .HasForeignKey("EventId")
                        .IsRequired()
                        .HasConstraintName("FK__security___event__0C50D423");

                    b.HasOne("LabManagement.DAL.Models.User", "Security")
                        .WithMany("SecurityLogs")
                        .HasForeignKey("SecurityId")
                        .IsRequired()
                        .HasConstraintName("FK__security___secur__0D44F85C");

                    b.Navigation("Event");

                    b.Navigation("Security");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.UserDepartment", b =>
                {
                    b.HasOne("LabManagement.DAL.Models.Department", "Department")
                        .WithMany("UserDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__user_depa__depar__74AE549C");

                    b.HasOne("LabManagement.DAL.Models.User", "User")
                        .WithMany("UserDepartments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__user_depa__user___73BA3083");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.ActivityType", b =>
                {
                    b.Navigation("LabEvents");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Department", b =>
                {
                    b.Navigation("Labs");

                    b.Navigation("UserDepartments");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.Lab", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Equipment");

                    b.Navigation("LabEvents");

                    b.Navigation("LabZones");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabEvent", b =>
                {
                    b.Navigation("EventParticipants");

                    b.Navigation("Notifications");

                    b.Navigation("SecurityLogs");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.LabZone", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LabEvents");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("LabManagement.DAL.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("EventParticipants");

                    b.Navigation("LabEvents");

                    b.Navigation("Labs");

                    b.Navigation("Notifications");

                    b.Navigation("SecurityLogs");

                    b.Navigation("UserDepartments");
                });
#pragma warning restore 612, 618
        }
    }
}
