using AutoMapper;
using LabManagement.BLL.DTOs;
using LabManagement.DAL.Models;

namespace LabManagement.BLL.Mappings
{
    public class NotificationProfile : Profile
    {
        public NotificationProfile()
        {
            // Entity → DTO (for GET operations)
            CreateMap<Notification, NotificationDTO>()
                .ForMember(dest => dest.NotificationId, opt => opt.MapFrom(src => src.NotificationId))
                .ForMember(dest => dest.RecipientId, opt => opt.MapFrom(src => src.RecipientId))
                .ForMember(dest => dest.EventId, opt => opt.MapFrom(src => src.EventId))
                .ForMember(dest => dest.Message, opt => opt.MapFrom(src => src.Message))
                .ForMember(dest => dest.SentAt, opt => opt.MapFrom(src => src.SentAt))
                .ForMember(dest => dest.IsRead, opt => opt.MapFrom(src => src.IsRead));

            // CreateDTO → Entity (for POST operations)
            CreateMap<CreateNotificationDTO, Notification>()
                .ForMember(dest => dest.NotificationId, opt => opt.Ignore()) // Auto-generated by DB
                .ForMember(dest => dest.RecipientId, opt => opt.MapFrom(src => src.RecipientId))
                .ForMember(dest => dest.EventId, opt => opt.MapFrom(src => src.EventId))
                .ForMember(dest => dest.Message, opt => opt.MapFrom(src => src.Message))
                .ForMember(dest => dest.SentAt, opt => opt.Ignore()) // Set in service
                .ForMember(dest => dest.IsRead, opt => opt.MapFrom(src => src.IsRead))
                .ForMember(dest => dest.Event, opt => opt.Ignore()) // Navigation property
                .ForMember(dest => dest.Recipient, opt => opt.Ignore()); // Navigation property

            // UpdateDTO → Entity (for PUT operations)
            CreateMap<UpdateNotificationDTO, Notification>()
                .ForMember(dest => dest.NotificationId, opt => opt.Ignore()) // Don't update ID
                .ForMember(dest => dest.RecipientId, opt => opt.Ignore()) // Don't update foreign keys
                .ForMember(dest => dest.EventId, opt => opt.Ignore()) // Don't update foreign keys
                .ForMember(dest => dest.Message, opt => opt.Condition(src => src.Message != null))
                .ForMember(dest => dest.SentAt, opt => opt.Ignore()) // Don't update timestamp
                .ForMember(dest => dest.IsRead, opt => opt.Condition(src => src.IsRead != null))
                .ForMember(dest => dest.Event, opt => opt.Ignore()) // Navigation property
                .ForMember(dest => dest.Recipient, opt => opt.Ignore()); // Navigation property
        }
    }
}
